_target_: ptls.nn.AggFeatureSeqEncoder
embeddings:
  mcc:
    in: 100
  channel_type:
    in: 4
  currency:
    in: 4
  trx_category:
    in: 10
numeric_values:
  amount: identity
was_logified: true
log_scale_factor: 1
