train:
  _target_: ptls.data_load.datasets.parquet_dataset.ParquetDataset
  shuffle_files: true
  i_filters:
    - _target_: ptls.data_load.iterable_processing.SeqLenFilter
      min_seq_len: 30
      max_seq_len: 100
    - _target_: ptls.data_load.iterable_processing.FeatureFilter
      # drop_feature_names:
      #   - app_id
      #   - product
      drop_non_iterable: false
    - _target_: ptls.data_load.iterable_processing.IterableShuffle
      buffer_size: 10000
  data_files:
    _target_: ptls.data_load.datasets.parquet_file_scan
    file_path: data/train_trx.parquet
    valid_rate: 0.05
    return_part: train

valid:
  _target_: ptls.data_load.datasets.parquet_dataset.ParquetDataset
  i_filters:
    - _target_: ptls.data_load.iterable_processing.SeqLenFilter
      min_seq_len: 30
      max_seq_len: 100
    - _target_: ptls.data_load.iterable_processing.FeatureFilter
      # drop_feature_names:
      #   - app_id
      #   - product
      drop_non_iterable: false
  data_files:
    _target_: ptls.data_load.datasets.parquet_file_scan
    file_path: data/train_trx.parquet
    valid_rate: 0.05
    return_part: valid

test:
  _target_: ptls.data_load.datasets.parquet_dataset.ParquetDataset
  i_filters:
    - _target_: ptls.data_load.iterable_processing.SeqLenFilter
      min_seq_len: 30
      max_seq_len: 100
    - _target_: ptls.data_load.iterable_processing.FeatureFilter
      # drop_feature_names:
      #   - product
      drop_non_iterable: false
  data_files:
    _target_: ptls.data_load.datasets.parquet_file_scan
    file_path: data/test_trx.parquet

